version: '3.8'

services:
  user-services:
    image: node:18-alpine
    restart: on-failure
    build: 
      context: ./user-services
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-services-database-postgres

  user-services-database-postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./user-services/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./user-services/volumes/postgres_data:/var/lib/postgresql/data

