version: '3.8'

services:
  user-services:
    restart: on-failure
    build: 
      context: ./user-services
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # command: npm run start
    depends_on:
      - user-services-database

  user-services-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-services-database
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

