version: '3'

services:
  user-services-database-postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudcurriculum
    volumes:
      - ./user-services-database-postgres:/var/lib/postgresql/data

  product-services-database-mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db

  order-services-database-postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudcurriculum
    volumes:
      - ./order-services-database-postgres:/var/lib/postgresql/data

  user-services:
    build: 
      context: ./user-services
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URI=postgresql://postgres:password@user-services-database-postgres:5432/postgres
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - user-services-database-postgres

  product-services:
    build: 
      context: ./product-services
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - MONGODB_HOST=product-services-database-mongodb
      - MONGODB_PORT=27017
    depends_on:
      - product-services-database-mongodb

  order-services:
    build: 
      context: ./order-services
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URI=postgresql://postgres:password@order-services-database-postgres:5433/postgres
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - order-services-database-postgres

volumes:
  user-services-database-postgres:
  mongodb-data:
  order-services-database-postgres:
